# Generated by Django 3.1.7 on 2021-03-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='Active')),
                ('position', models.CharField(choices=[('VL', 'Vertical Left'), ('VR', 'Vertical Right'), ('H', 'Horizontal')], max_length=64)),
            ],
            options={
                'verbose_name': 'Barre de navigation',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('position', models.IntegerField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navbar.navbar')),
            ],
            options={
                'verbose_name': 'Lien',
                'ordering': ['position'],
            },
        ),
    ]
