# Generated by Django 3.1.7 on 2021-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='style',
            field=models.IntegerField(choices=[(1, 'navbar-light bg-light'), (2, 'navbar-dark bg-dark'), (3, 'navbar-dark bg-primary')], default=1),
        ),
    ]
